version: '3.7'

services:

  # My tweetapp frontend application
  tweetappreact:
    image: singhswaraj/tweetappreact:latest
    container_name: tweetappreact
    ports:
      - "80:3000"
      - "443:3000"
    volumes:
      - ./tweetappreact:/tweetappreact
      - ./tweetappreact/node_modules:/tweetappreact/node_modules
    networks:
      - elk

  
  # My tweetapp backend application
  tweetapp:
    image: singhswaraj/tweetapp:latest
    container_name: tweetapp
    ports:
      - "8880:8880"
    volumes:
      - ./tweetapp/logs:/logs:rw
    networks:
      - elk
    depends_on:
      - tweetappreact
  
  # Everything related to ELK is below here
  
  setup:
    build:
      context: tooling/setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    volumes:
      - ./tooling/setup:/state:Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./tooling/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./tooling/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./tooling/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
      - ./tweetapp/logs/spring.log:/logs/spring.log:z
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: tooling/kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./tooling/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - "5601:5601"
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch


networks:
  elk:
    driver: bridge
volumes:
  elasticsearch:
